-- StarRocks source tables for SRM batch report validation.
-- Tables:
--   srm_orders
--   srm_orderline
--   srm_orderdeliverybatch
--   srm_attachment

CREATE TABLE IF NOT EXISTS srm_orders (
    `uuid` VARCHAR(64) NOT NULL,
    `version` BIGINT NULL,
    `created` DATETIME NULL,
    `creatorNS` VARCHAR(128) NULL,
    `creatorId` VARCHAR(128) NULL,
    `creatorName` VARCHAR(255) NULL,
    `lastModified` DATETIME NULL,
    `lastModifierNS` VARCHAR(128) NULL,
    `lastModifierId` VARCHAR(128) NULL,
    `lastModifierName` VARCHAR(255) NULL,
    `tenant` VARCHAR(64) NULL,
    `id` VARCHAR(128) NULL,
    `number` VARCHAR(128) NULL,
    `retailerId` VARCHAR(128) NULL,
    `vendorId` VARCHAR(128) NULL,
    `vendorName` VARCHAR(512) NULL,
    `state` VARCHAR(64) NULL,
    `read` TINYINT NULL,
    `type` VARCHAR(128) NULL,
    `companyCode` VARCHAR(128) NULL,
    `companyName` VARCHAR(512) NULL,
    `unitRef` VARCHAR(128) NULL,
    `unitRefCode` VARCHAR(128) NULL,
    `receiver` VARCHAR(512) NULL,
    `receiverCode` VARCHAR(128) NULL,
    `warehouse` VARCHAR(512) NULL,
    `warehouseCode` VARCHAR(128) NULL,
    `address` STRING NULL,
    `contactor` VARCHAR(255) NULL,
    `phone` VARCHAR(128) NULL,
    `purchaser` VARCHAR(255) NULL,
    `expiredDate` DATETIME NULL,
    `arrivalDate` DATETIME NULL,
    `amount` DECIMAL(18, 6) NULL,
    `tax` DECIMAL(18, 6) NULL,
    `taxAmount` DECIMAL(18, 6) NULL,
    `qty` DECIMAL(18, 6) NULL,
    `confirmDate` DATETIME NULL,
    `deliveryTime` DATETIME NULL,
    `printCount` BIGINT NULL,
    `lastPrintTime` DATETIME NULL,
    `remark` STRING NULL,
    `dateCreated` DATETIME NULL,
    `currency` VARCHAR(64) NULL,
    `munit` VARCHAR(128) NULL,
    `logisticsMode` VARCHAR(128) NULL,
    `trackingNumber` VARCHAR(255) NULL,
    `extendName0` VARCHAR(255) NULL,
    `extendValue0` STRING NULL,
    `extendName1` VARCHAR(255) NULL,
    `extendValue1` STRING NULL,
    `extendName2` VARCHAR(255) NULL,
    `extendValue2` STRING NULL,
    `extendName3` VARCHAR(255) NULL,
    `extendValue3` STRING NULL,
    `extendName4` VARCHAR(255) NULL,
    `extendValue4` STRING NULL,
    `extendName5` VARCHAR(255) NULL,
    `extendValue5` STRING NULL,
    `extendName6` VARCHAR(255) NULL,
    `extendValue6` STRING NULL,
    `extendName7` VARCHAR(255) NULL,
    `extendValue7` STRING NULL,
    `extendName8` VARCHAR(255) NULL,
    `extendValue8` STRING NULL,
    `extendName9` VARCHAR(255) NULL,
    `extendValue9` STRING NULL,
    `deliveryQty` DECIMAL(18, 6) NULL,
    `deliveryAmount` DECIMAL(18, 6) NULL,
    `receivedQty` DECIMAL(18, 6) NULL,
    `receivedAmount` DECIMAL(18, 6) NULL,
    `receivedQpcQty` DECIMAL(18, 6) NULL,
    `targetLatitude` DECIMAL(18, 8) NULL,
    `targetLongitude` DECIMAL(18, 8) NULL,
    `dockUuid` VARCHAR(64) NULL,
    `dockCode` VARCHAR(128) NULL,
    `dockName` VARCHAR(512) NULL,
    `dockType` VARCHAR(128) NULL,
    `deliveryStartTime` DATETIME NULL,
    `deliveryEndTime` DATETIME NULL,
    `purchaserCode` VARCHAR(128) NULL,
    `purchaserName` VARCHAR(255) NULL,
    `srcNumber` VARCHAR(128) NULL,
    `srcType` VARCHAR(128) NULL,
    `lineCount` BIGINT NULL,
    `deductionAmount` DECIMAL(18, 6) NULL,
    `readCount` BIGINT NULL,
    `carrierCode` VARCHAR(128) NULL,
    `carrierName` VARCHAR(512) NULL,
    `balUnitId` VARCHAR(128) NULL,
    `balUnitName` VARCHAR(512) NULL,
    `balUnitType` VARCHAR(128) NULL,
    `appointmentQty` DECIMAL(18, 6) NULL,
    `appointmentAmount` DECIMAL(18, 6) NULL,
    `standardAppointmentQty` DECIMAL(18, 6) NULL,
    `bizType` VARCHAR(128) NULL,
    `multiDelivery` VARCHAR(64) NULL,
    `shipStd` VARCHAR(128) NULL,
    `allowqty` DECIMAL(18, 6) NULL,
    `allowamount` DECIMAL(18, 6) NULL,
    `requireqty` DECIMAL(18, 6) NULL,
    `requireamount` DECIMAL(18, 6) NULL,
    `expectedqty` DECIMAL(18, 6) NULL,
    `expectedamount` DECIMAL(18, 6) NULL,
    `oosqty` DECIMAL(18, 6) NULL,
    `oosamount` DECIMAL(18, 6) NULL,
    `expectconfirm` VARCHAR(64) NULL,
    `batchconfirmqtyid` VARCHAR(128) NULL,
    `oosconfirmdate` DATETIME NULL,
    `batchconfirmqtycount` BIGINT NULL,
    `deliveryreplaceqty` DECIMAL(18, 6) NULL,
    `deliveryreplaceamount` DECIMAL(18, 6) NULL,
    `receivedReplaceQty` DECIMAL(18, 6) NULL,
    `receivedReplaceAmount` DECIMAL(18, 6) NULL,
    `paymentState` VARCHAR(64) NULL,
    `overdueState` VARCHAR(64) NULL,
    `processFactoryId` VARCHAR(128) NULL,
    `processFactoryName` VARCHAR(512) NULL,
    `carrierAgentCode` VARCHAR(128) NULL,
    `carrierAgentName` VARCHAR(512) NULL
)
DUPLICATE KEY(`uuid`)
DISTRIBUTED BY HASH(`uuid`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS srm_orderline (
    `uuid` VARCHAR(64) NOT NULL,
    `version` BIGINT NULL,
    `created` DATETIME NULL,
    `creatorNS` VARCHAR(128) NULL,
    `creatorId` VARCHAR(128) NULL,
    `creatorName` VARCHAR(255) NULL,
    `lastModified` DATETIME NULL,
    `lastModifierNS` VARCHAR(128) NULL,
    `lastModifierId` VARCHAR(128) NULL,
    `lastModifierName` VARCHAR(255) NULL,
    `tenant` VARCHAR(64) NULL,
    `lineNo` BIGINT NULL,
    `skuLineNo` BIGINT NULL,
    `orderId` VARCHAR(64) NULL,
    `skuCode` VARCHAR(128) NULL,
    `barcode` VARCHAR(128) NULL,
    `skuName` VARCHAR(512) NULL,
    `skuType` VARCHAR(128) NULL,
    `skuText` STRING NULL,
    `image` STRING NULL,
    `amount` DECIMAL(18, 6) NULL,
    `taxAmount` DECIMAL(18, 6) NULL,
    `tax` DECIMAL(18, 6) NULL,
    `qty` DECIMAL(18, 6) NULL,
    `deliveryQty` DECIMAL(18, 6) NULL,
    `price` DECIMAL(18, 6) NULL,
    `taxrate` DECIMAL(18, 6) NULL,
    `unit` VARCHAR(128) NULL,
    `qpcText` VARCHAR(255) NULL,
    `qpcQty` DECIMAL(18, 6) NULL,
    `remark` STRING NULL,
    `oosQty` DECIMAL(18, 6) NULL,
    `caseMunit` VARCHAR(128) NULL,
    `actualQpcQty` DECIMAL(18, 6) NULL,
    `exempt` VARCHAR(64) NULL,
    `receiverCode` VARCHAR(128) NULL,
    `receiverName` VARCHAR(512) NULL,
    `lineExempt` VARCHAR(64) NULL,
    `singlePrice` DECIMAL(18, 6) NULL,
    `extendName0` VARCHAR(255) NULL,
    `extendValue0` STRING NULL,
    `extendName1` VARCHAR(255) NULL,
    `extendValue1` STRING NULL,
    `extendName2` VARCHAR(255) NULL,
    `extendValue2` STRING NULL,
    `extendName3` VARCHAR(255) NULL,
    `extendValue3` STRING NULL,
    `extendName4` VARCHAR(255) NULL,
    `extendValue4` STRING NULL,
    `extendName5` VARCHAR(255) NULL,
    `extendValue5` STRING NULL,
    `extendName6` VARCHAR(255) NULL,
    `extendValue6` STRING NULL,
    `extendName7` VARCHAR(255) NULL,
    `extendValue7` STRING NULL,
    `extendName8` VARCHAR(255) NULL,
    `extendValue8` STRING NULL,
    `extendName9` VARCHAR(255) NULL,
    `extendValue9` STRING NULL,
    `standardDeliveryQty` DECIMAL(18, 6) NULL,
    `toleranceTag` VARCHAR(128) NULL,
    `deliveryAmount` DECIMAL(18, 6) NULL,
    `receivedQty` DECIMAL(18, 6) NULL,
    `receivedAmount` DECIMAL(18, 6) NULL,
    `receivedQpcQty` DECIMAL(18, 6) NULL,
    `content` STRING NULL,
    `deductionAmount` DECIMAL(18, 6) NULL,
    `deductionPrice` DECIMAL(18, 6) NULL,
    `deductionSinglePrice` DECIMAL(18, 6) NULL,
    `expectedQty` DECIMAL(18, 6) NULL,
    `expectedQpcQty` DECIMAL(18, 6) NULL,
    `expectedAmount` DECIMAL(18, 6) NULL,
    `state` VARCHAR(64) NULL,
    `appointmentQty` DECIMAL(18, 6) NULL,
    `appointmentAmount` DECIMAL(18, 6) NULL,
    `standardAppointmentQty` DECIMAL(18, 6) NULL,
    `appointmentQpcQty` DECIMAL(18, 6) NULL,
    `plateAdvice` VARCHAR(255) NULL,
    `detailLineNo` BIGINT NULL,
    `allowqty` DECIMAL(18, 6) NULL,
    `allowqpcqty` DECIMAL(18, 6) NULL,
    `allowamount` DECIMAL(18, 6) NULL,
    `requireqty` DECIMAL(18, 6) NULL,
    `requireqpcqty` DECIMAL(18, 6) NULL,
    `requireamount` DECIMAL(18, 6) NULL,
    `oosqpcqty` DECIMAL(18, 6) NULL,
    `oosamount` DECIMAL(18, 6) NULL,
    `deliveryreplaceqty` DECIMAL(18, 6) NULL,
    `deliveryreplaceqpcqty` DECIMAL(18, 6) NULL,
    `deliveryreplaceamount` DECIMAL(18, 6) NULL,
    `expectedqpctext` VARCHAR(255) NULL,
    `actualexpectedqpcqty` DECIMAL(18, 6) NULL,
    `receivedReplaceQty` DECIMAL(18, 6) NULL,
    `receivedReplaceQpcQty` DECIMAL(18, 6) NULL,
    `receivedReplaceAmount` DECIMAL(18, 6) NULL,
    `orderLineNo` BIGINT NULL
)
DUPLICATE KEY(`uuid`)
DISTRIBUTED BY HASH(`orderId`, `uuid`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS srm_orderdeliverybatch (
    `uuid` VARCHAR(64) NOT NULL,
    `tenant` VARCHAR(64) NULL,
    `orderId` VARCHAR(64) NULL,
    `orderLineUuid` VARCHAR(64) NULL,
    `tranId` VARCHAR(128) NULL,
    `deliveryId` VARCHAR(128) NULL,
    `lineNo` BIGINT NULL,
    `skuLineNo` BIGINT NULL,
    `skuCode` VARCHAR(128) NULL,
    `barcode` VARCHAR(128) NULL,
    `skuName` VARCHAR(512) NULL,
    `content` STRING NULL,
    `skuType` VARCHAR(128) NULL,
    `skuText` STRING NULL,
    `image` STRING NULL,
    `price` DECIMAL(18, 6) NULL,
    `caseMunit` VARCHAR(128) NULL,
    `unit` VARCHAR(128) NULL,
    `qpcText` VARCHAR(255) NULL,
    `qpcQty` DECIMAL(18, 6) NULL,
    `remark` STRING NULL,
    `deliveryQty` DECIMAL(18, 6) NULL,
    `deliveryAmount` DECIMAL(18, 6) NULL,
    `actualQpcQty` DECIMAL(18, 6) NULL,
    `deliveryTime` DATETIME NULL,
    `productionTime` DATETIME NULL,
    `expiredTime` DATETIME NULL
)
DUPLICATE KEY(`uuid`)
DISTRIBUTED BY HASH(`orderId`, `orderLineUuid`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS srm_attachment (
    `uuid` VARCHAR(64) NOT NULL,
    `version` BIGINT NULL,
    `created` DATETIME NULL,
    `creatorNS` VARCHAR(128) NULL,
    `creatorId` VARCHAR(128) NULL,
    `creatorName` VARCHAR(255) NULL,
    `lastModified` DATETIME NULL,
    `lastModifierNS` VARCHAR(128) NULL,
    `lastModifierId` VARCHAR(128) NULL,
    `lastModifierName` VARCHAR(255) NULL,
    `tenant` VARCHAR(64) NULL,
    `refId` VARCHAR(64) NULL,
    `refType` VARCHAR(128) NULL,
    `attachmentName` VARCHAR(1024) NULL,
    `storeId` VARCHAR(255) NULL,
    `removed` TINYINT NULL,
    `url` STRING NULL,
    `extendName0` VARCHAR(255) NULL,
    `extendValue0` STRING NULL,
    `extendName1` VARCHAR(255) NULL,
    `extendValue1` STRING NULL,
    `extendName2` VARCHAR(255) NULL,
    `extendValue2` STRING NULL,
    `extendName3` VARCHAR(255) NULL,
    `extendValue3` STRING NULL,
    `extendName4` VARCHAR(255) NULL,
    `extendValue4` STRING NULL,
    `extendName5` VARCHAR(255) NULL,
    `extendValue5` STRING NULL,
    `extendName6` VARCHAR(255) NULL,
    `extendValue6` STRING NULL,
    `extendName7` VARCHAR(255) NULL,
    `extendValue7` STRING NULL,
    `extendName8` VARCHAR(255) NULL,
    `extendValue8` STRING NULL,
    `extendName9` VARCHAR(255) NULL,
    `extendValue9` STRING NULL
)
DUPLICATE KEY(`uuid`)
DISTRIBUTED BY HASH(`refId`, `uuid`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);
