-- StarRocks source tables for full-table OA Ecology extraction.
-- Source system: oa
-- Source database: ecology
-- Naming: ods_{system}_{database}_{table}_{sync_type}
-- Suffix: df = daily full snapshot
-- Tables:
--   ods_oa_ecology_formtable_main_283_df
--   ods_oa_ecology_workflow_requestbase_df
--   ods_oa_ecology_docdetail_df
--   ods_oa_ecology_docimagefile_df
--   ods_oa_ecology_imagefile_df

CREATE TABLE IF NOT EXISTS ods_oa_ecology_formtable_main_283_df (
    `id` INT NOT NULL,
    `requestid` INT NULL,
    `bt` STRING NULL,
    `bh` STRING NULL,
    `sqrq` VARCHAR(10) NULL,
    `sqr` INT NULL,
    `sqbm` INT NULL,
    `sqgs` INT NULL,
    `qsbt` STRING NULL,
    `nrgk` STRING NULL,
    `fj` STRING NULL,
    `xgfzr` STRING NULL,
    `bz` STRING NULL,
    `csr` STRING NULL,
    `qslb` INT NULL,
    `mbxz` STRING NULL,
    `xydjfjsc` STRING NULL,
    `xyxsfjyl` STRING NULL,
    `mdmc` STRING NULL,
    `mdlx` VARCHAR(100) NULL,
    `szzq` VARCHAR(100) NULL,
    `mdbm` VARCHAR(100) NULL,
    `ycxssqh` STRING NULL,
    `ycxsqd` STRING NULL,
    `yyzz` STRING NULL,
    `ycxsxkz` STRING NULL,
    `yczyxqksrq` VARCHAR(10) NULL,
    `yczyxqjsrq` VARCHAR(10) NULL,
    `mdms` INT NULL,
    `sfdlxp` INT NULL,
    `yczdyyyzz` STRING NULL,
    `wfzt` STRING NULL,
    `sfyyjylsym` INT NULL,
    `dd` STRING NULL,
    `dzd` STRING NULL,
    `ddsyxtgy` STRING NULL,
    `ddsyxtbgy` STRING NULL,
    `dzdsyxtgy` STRING NULL,
    `dzdsyxtbgy` STRING NULL,
    `qyslcid` VARCHAR(200) NULL,
    `yyzzfrxm` VARCHAR(200) NULL,
    `frdhhm` VARCHAR(200) NULL,
    `frsfzh` VARCHAR(200) NULL,
    `mddz` VARCHAR(200) NULL,
    `sys_workflowid` INT NULL,
    `mdms1` INT NULL
)
DUPLICATE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS ods_oa_ecology_workflow_requestbase_df (
    `REQUESTID` INT NOT NULL,
    `WORKFLOWID` INT NULL,
    `LASTNODEID` INT NULL,
    `LASTNODETYPE` VARCHAR(1) NULL,
    `CURRENTNODEID` INT NULL,
    `CURRENTNODETYPE` VARCHAR(1) NULL,
    `STATUS` VARCHAR(1000) NULL,
    `PASSEDGROUPS` INT NULL,
    `TOTALGROUPS` INT NULL,
    `REQUESTNAME` VARCHAR(1000) NULL,
    `CREATER` INT NULL,
    `CREATEDATE` VARCHAR(10) NULL,
    `CREATETIME` VARCHAR(8) NULL,
    `LASTOPERATOR` INT NULL,
    `LASTOPERATEDATE` VARCHAR(10) NULL,
    `LASTOPERATETIME` VARCHAR(8) NULL,
    `DELETED` INT NULL,
    `CREATERTYPE` INT NULL,
    `LASTOPERATORTYPE` INT NULL,
    `NODEPASSTIME` DOUBLE NULL,
    `NODELEFTTIME` DOUBLE NULL,
    `DOCIDS` STRING NULL,
    `CRMIDS` STRING NULL,
    `HRMIDS_TEMP` STRING NULL,
    `PRJIDS` STRING NULL,
    `CPTIDS` STRING NULL,
    `REQUESTLEVEL` INT NULL,
    `REQUESTMARK` VARCHAR(800) NULL,
    `MESSAGETYPE` INT NULL,
    `MAINREQUESTID` INT NULL,
    `CURRENTSTATUS` INT NULL,
    `LASTSTATUS` VARCHAR(480) NULL,
    `ISMULTIPRINT` INT NULL,
    `CHATSTYPE` INT NULL,
    `ECOLOGY_PINYIN_SEARCH` VARCHAR(1000) NULL,
    `HRMIDS` STRING NULL,
    `REQUESTNAMENEW` STRING NULL,
    `FORMSIGNATUREMD5` STRING NULL,
    `DATAAGGREGATED` VARCHAR(1) NULL,
    `secLevel` VARCHAR(1) NULL,
    `secdocid` VARCHAR(500) NULL,
    `remindTypes` VARCHAR(40) NULL,
    `lastFeedBackDate` VARCHAR(10) NULL,
    `lastFeedBackTime` VARCHAR(8) NULL,
    `lastfeedbackoperator` INT NULL,
    `requestnamehtmlnew` VARCHAR(4000) NULL,
    `secvalidity` VARCHAR(50) NULL,
    `secencKey` VARCHAR(200) NULL,
    `seccrc` VARCHAR(100) NULL
)
DUPLICATE KEY(`REQUESTID`)
DISTRIBUTED BY HASH(`REQUESTID`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS ods_oa_ecology_docdetail_df (
    `ID` INT NOT NULL,
    `MAINCATEGORY` INT NULL,
    `SUBCATEGORY` INT NULL,
    `SECCATEGORY` INT NULL,
    `DOCTYPE` INT NULL,
    `DOCLANGURAGE` INT NULL,
    `DOCAPPROVABLE` VARCHAR(1) NULL,
    `DOCREPLYABLE` VARCHAR(1) NULL,
    `ISREPLY` VARCHAR(1) NULL,
    `REPLYDOCID` INT NULL,
    `DOCSUBJECT` VARCHAR(1000) NULL,
    `DOCSHARETYPE` VARCHAR(1) NULL,
    `SHAREROLEID` INT NULL,
    `DOCPUBLISHTYPE` VARCHAR(1) NULL,
    `ITEMID` INT NULL,
    `ITEMMAINCATEGORYID` INT NULL,
    `HRMRESID` INT NULL,
    `CRMID` INT NULL,
    `PROJECTID` INT NULL,
    `FINANCEID` INT NULL,
    `FINANCEREFENCEID1` INT NULL,
    `FINANCEREFENCEID2` INT NULL,
    `DOCCREATERID` INT NULL,
    `DOCDEPARTMENTID` INT NULL,
    `DOCCREATEDATE` VARCHAR(10) NULL,
    `DOCCREATETIME` VARCHAR(8) NULL,
    `DOCLASTMODUSERID` INT NULL,
    `DOCLASTMODDATE` VARCHAR(10) NULL,
    `DOCLASTMODTIME` VARCHAR(8) NULL,
    `DOCAPPROVEUSERID` INT NULL,
    `DOCAPPROVEDATE` VARCHAR(10) NULL,
    `DOCAPPROVETIME` VARCHAR(8) NULL,
    `DOCARCHIVEUSERID` INT NULL,
    `DOCARCHIVEDATE` VARCHAR(10) NULL,
    `DOCARCHIVETIME` VARCHAR(8) NULL,
    `PARENTIDS` VARCHAR(1000) NULL,
    `ASSETID` INT NULL,
    `OWNERID` INT NULL,
    `KEYWORD` VARCHAR(1000) NULL,
    `ACCESSORYCOUNT` INT NULL,
    `REPLAYDOCCOUNT` INT NULL,
    `USERTYPE` VARCHAR(1) NULL,
    `DOCNO` VARCHAR(800) NULL,
    `CANCOPY` VARCHAR(1) NULL,
    `CANREMIND` VARCHAR(1) NULL,
    `COUNTMARK` INT NULL,
    `SUMMARK` INT NULL,
    `SUMREADCOUNT` INT NULL,
    `ORDERABLE` VARCHAR(1) NULL,
    `DOCEXTENDNAME` VARCHAR(10) NULL,
    `DOCCODE` VARCHAR(1000) NULL,
    `DOCEDITION` INT NULL,
    `DOCEDITIONID` INT NULL,
    `ISHISTORY` INT NULL,
    `MAINDOC` INT NULL,
    `APPROVETYPE` INT NULL,
    `READOPTERCANPRINT` INT NULL,
    `DOCVALIDUSERID` INT NULL,
    `DOCVALIDDATE` VARCHAR(10) NULL,
    `DOCVALIDTIME` VARCHAR(8) NULL,
    `DOCPUBUSERID` INT NULL,
    `DOCPUBDATE` VARCHAR(10) NULL,
    `DOCPUBTIME` VARCHAR(8) NULL,
    `DOCREOPENUSERID` INT NULL,
    `DOCREOPENDATE` VARCHAR(10) NULL,
    `DOCREOPENTIME` VARCHAR(8) NULL,
    `DOCINVALUSERID` INT NULL,
    `DOCINVALDATE` VARCHAR(10) NULL,
    `DOCINVALTIME` VARCHAR(8) NULL,
    `DOCCANCELUSERID` INT NULL,
    `DOCCANCELDATE` VARCHAR(10) NULL,
    `DOCCANCELTIME` VARCHAR(8) NULL,
    `SELECTEDPUBMOULDID` INT NULL,
    `CHECKOUTSTATUS` VARCHAR(1) NULL,
    `CHECKOUTUSERID` INT NULL,
    `CHECKOUTUSERTYPE` VARCHAR(1) NULL,
    `CHECKOUTDATE` VARCHAR(10) NULL,
    `CHECKOUTTIME` VARCHAR(8) NULL,
    `HASUSEDTEMPLET` VARCHAR(1) NULL,
    `INVALIDATIONDATE` VARCHAR(10) NULL,
    `DOCCREATERTYPE` VARCHAR(1) NULL,
    `DOCLASTMODUSERTYPE` VARCHAR(1) NULL,
    `DOCAPPROVEUSERTYPE` VARCHAR(1) NULL,
    `DOCVALIDUSERTYPE` VARCHAR(1) NULL,
    `DOCINVALUSERTYPE` VARCHAR(1) NULL,
    `DOCARCHIVEUSERTYPE` VARCHAR(1) NULL,
    `DOCCANCELUSERTYPE` VARCHAR(1) NULL,
    `DOCPUBUSERTYPE` VARCHAR(1) NULL,
    `DOCREOPENUSERTYPE` VARCHAR(1) NULL,
    `OWNERTYPE` VARCHAR(1) NULL,
    `DOCSTATUS` INT NULL,
    `CANPRINTEDNUM` INT NULL,
    `HASPRINTEDNUM` INT NULL,
    `APPROVEREQUESTID` INT NULL,
    `FROMWORKFLOW` INT NULL,
    `ISTOP` INT NULL,
    `TOPDATE` VARCHAR(80) NULL,
    `TOPTIME` VARCHAR(64) NULL,
    `TOPSTARTDATE` VARCHAR(80) NULL,
    `TOPENDDATE` VARCHAR(80) NULL,
    `INVALIDREQUESTID` INT NULL,
    `EDITMOULDID` INT NULL,
    `ECOLOGY_PINYIN_SEARCH` VARCHAR(1000) NULL,
    `DOCVESTIN` INT NULL,
    `sumDownload` INT NULL,
    `secretLevel` INT NULL,
    `replyremind` INT NULL,
    `scheduledreleasedate` VARCHAR(10) NULL,
    `secretvalidity` VARCHAR(64) NULL,
    `themeshowpic` VARCHAR(64) NULL,
    `ISOPENCOLLA` VARCHAR(10) NULL,
    `docsmalledition` INT NULL,
    `bigedition` INT NULL,
    `publiclabel` VARCHAR(2000) NULL,
    `privatelabel` VARCHAR(2000) NULL
)
DUPLICATE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS ods_oa_ecology_docimagefile_df (
    `ID` INT NOT NULL,
    `DOCID` INT NULL,
    `IMAGEFILEID` INT NULL,
    `IMAGEFILENAME` VARCHAR(1000) NULL,
    `IMAGEFILEDESC` VARCHAR(1000) NULL,
    `IMAGEFILEWIDTH` INT NULL,
    `IMAGEFILEHEIGHT` INT NULL,
    `IMAGEFIELSIZE` INT NULL,
    `DOCFILETYPE` VARCHAR(16) NULL,
    `VERSIONID` INT NULL,
    `versiondetail` VARCHAR(1000) NULL,
    `ISEXTFILE` VARCHAR(1) NULL,
    `HASUSEDTEMPLET` VARCHAR(1) NULL,
    `SIGNATURECOUNT` INT NULL,
    `operateuserid` INT NULL,
    `operatedate` VARCHAR(800) NULL,
    `operatetime` VARCHAR(800) NULL,
    `cadcheckoutstatus` INT NULL,
    `cadcheckoutid` INT NULL,
    `cadcheckoutdate` VARCHAR(10) NULL,
    `cadcheckouttime` VARCHAR(8) NULL
)
DUPLICATE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);

CREATE TABLE IF NOT EXISTS ods_oa_ecology_imagefile_df (
    `IMAGEFILEID` INT NOT NULL,
    `IMAGEFILENAME` VARCHAR(1000) NULL,
    `IMAGEFILETYPE` VARCHAR(1000) NULL,
    `IMAGEFILE` STRING NULL,
    `IMAGEFILEUSED` INT NULL,
    `FILEREALPATH` VARCHAR(1000) NULL,
    `ISZIP` VARCHAR(1) NULL,
    `ISENCRYPT` VARCHAR(1) NULL,
    `FILESIZE` VARCHAR(160) NULL,
    `DOWNLOADS` INT NULL,
    `MINIIMGPATH` VARCHAR(1000) NULL,
    `IMGSIZE` VARCHAR(400) NULL,
    `ISFTP` VARCHAR(1) NULL,
    `FTPCONFIGID` INT NULL,
    `ISAESENCRYPT` INT NULL,
    `AESCODE` VARCHAR(1000) NULL,
    `TOKENKEY` VARCHAR(1000) NULL,
    `STORAGESTATUS` VARCHAR(1) NULL,
    `COMEFROM` VARCHAR(800) NULL,
    `OBJID` INT NULL,
    `OBJOTHERPARA` STRING NULL,
    `DELFILEREALPATH` VARCHAR(1) NULL,
    `mainimagefile` INT NULL,
    `secretLevel` INT NULL,
    `secretvalidity` VARCHAR(64) NULL,
    `sensitive_wtype` INT NULL,
    `sensitive_wtime` VARCHAR(19) NULL,
    `original_fileid` INT NULL,
    `signinfo` VARCHAR(500) NULL,
    `hashinfo` VARCHAR(500) NULL,
    `groupname` VARCHAR(250) NULL,
    `dfsfilename` VARCHAR(250) NULL,
    `md5` VARCHAR(255) NULL,
    `ofilewjid` VARCHAR(100) NULL,
    `ofileetag` VARCHAR(100) NULL,
    `lastModifiedDateTime` VARCHAR(100) NULL
)
DUPLICATE KEY(`IMAGEFILEID`)
DISTRIBUTED BY HASH(`IMAGEFILEID`) BUCKETS 12
PROPERTIES (
    "compression" = "LZ4",
    "datacache.enable" = "true",
    "enable_async_write_back" = "false",
    "enable_persistent_index" = "true",
    "persistent_index_type" = "LOCAL",
    "replication_num" = "1",
    "storage_volume" = "def_volume"
);
