apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-ai-review
  namespace: ds-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai-review.lsym.cn
      secretName: act-luck-tls
  rules:
    - host: ai-review.lsym.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: document-ai-review
                port:
                  number: 8000
