apiVersion: v1
kind: Service
metadata:
  name: document-ai-review
  namespace: ds-api
  labels:
    app: document-ai-review
spec:
  selector:
    app: document-ai-review
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
