#!/usr/bin/env python3
"""Generate the checked-in HTTP operation inventory from FastAPI OpenAPI."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


AI_SERVICE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = AI_SERVICE_ROOT.parent
OUTPUT_PATH = REPO_ROOT / "docs/api/openapi-operations.md"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")

if str(AI_SERVICE_ROOT) not in sys.path:
    sys.path.insert(0, str(AI_SERVICE_ROOT))

from app.main import app  # noqa: E402


def render_inventory() -> str:
    openapi = app.openapi()
    operations: list[tuple[str, str, str, str]] = []
    for path, path_item in sorted(openapi["paths"].items()):
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if not operation:
                continue
            tags = ", ".join(operation.get("tags") or ["untagged"])
            summary = " ".join(str(operation.get("summary") or "").split())
            operations.append((method.upper(), path, tags, summary))

    lines = [
        "# FastAPI Operation Inventory",
        "",
        "> Generated from `app.main:app`. Do not edit this file manually.",
        "> Regenerate with `cd ai-service && python scripts/generate_api_operation_inventory.py`.",
        "",
        f"Current schema contains **{len(openapi['paths'])} paths** and "
        f"**{len(operations)} HTTP operations**.",
        "",
        "| Method | Path | Tag | Summary |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{method}` | `{path}` | `{_escape_markdown_table_cell(tags)}` | "
        f"{_escape_markdown_table_cell(summary)} |"
        for method, path, tags, summary in operations
    )
    lines.append("")
    return "\n".join(lines)


def _escape_markdown_table_cell(value: str) -> str:
    return value.replace("|", "\\|")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in inventory differs from current OpenAPI",
    )
    args = parser.parse_args()
    expected = render_inventory()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"missing generated API inventory: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(
                "generated API inventory is stale; run "
                "`python scripts/generate_api_operation_inventory.py`",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
